config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "practices#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :practices, only: %i[index show] do
    resources :cards, only: %i[new create]
    resources :institutions, only: %i[index new create]
    get '/institutions/:google_places_id', to: 'institutions#show', as: 'institution'
  end
  resources :cards, only: %i[index show update destroy] do
    resources :studywords, only: :create
    resources :studyphrases, only: :create
    member do
      post :redo, :redophrase
    end
  end
  resources :studywords, only: :index # do
  #   resources :studyphrases, only: :index
  # end
end

app/models/practice.rb
class Practice < ApplicationRecord
  # association(see also the schema https://kitt.lewagon.com/db/101668)
  has_many :institutionspractices, dependent: :destroy
  has_many :institions, through: :institutionspractices

  has_many :practicekeywords, dependent: :destroy
  has_many :medicalkeywords, through: :practicekeywords

  has_many :cards, dependent: :destroy

  has_one_attached :photo

  validates_presence_of :name, :info, :japanese_name
  include PgSearch::Model
  # multisearchable against: [:name, :info]

  pg_search_scope :global_search,
  against: [:name, :info],
  associated_against: {
    medicalkeywords: [:term]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  def index
    # all practicies filtered by pundit policy(see app/policies)
    @practices = policy_scope(Practice)
    if params[:query].present?
      # @practices = @practices.global_search(params[:query])
      @practices = @practices.global_search(params[:query])
    end
    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.json { render json: @practices }
      format.text { render partial: "practices/list", locals: { practices: @practices }, formats: [:html] }
    end
  end

  def show
    @practice = Practice.find(params[:id])
    authorize @practice
  end
end

private

def practice_params
  params.require(:practice).permit(:name, :info, :photo)
end

app/views/practices/_descriptor.html.erb
<div class="practices-descriptor">
  <%# <h3><strong>What's Kenkou Match?</strong></h3> %>
  <%# <p>read more </p> %>
  <p><strong>We're here to help you find the right medical specialist to suit your needs.</strong></p>
  <p>Our unique <strong>"Kenkou Card"</strong> offers an ai-assisted study card to help you better communicate your needs to medical profressionals.</p>
</div>

app/views/practices/_list.html.erb
<p class="h3 practice-count">
  <% if params[:query].blank? %>
    <h3></h3>
  <% else %>
    <h3><%= pluralize practices.count, "result" %> for <code><%= params[:query] %></code></h3>
  <% end %>
</p>
<div class="practices-container">
  <div class="row scrollable">
    <% practices.each do |practice| %>
      <div class="col-6 col-lg-4">
        <%= render "practice_infos", practice: practice %>
      </div>
    <% end %>
  </div>
</div>

app/views/practices/_practice_infos.html.erb
<div class="practice-card d-flex justify-content-center align-items-center border border-info rounded-4 shadow p-3 bg-body rounded border-opacity-25 border-light">
  <div class="practice-infos">
    <img src="<%= practice.photo.attached? ? cl_image_path(practice.photo.key) :  'https://img.freepik.com/free-vector/doctor-medical-healthcare-pfrofessional-character-vector_53876-175176.jpg?size=626&ext=jpg&ga=GA1.1.1233122341.1682826076&semt=ais' %>" alt="">
    <div>
      <span class="card-text"><%= practice.name %></span>
    </div>
    <!-- <%if practice.photo.present?%>
        <%= cl_image_tag practice.photo.key, height: 300, width: 400, crop: :fill %>
      <%end%> -->
    <%= link_to practice_path(practice), class: 'fw-bold text-decoration-none practice-card-link' do %>
    </div>
  <% end %>
</div>

app/views/practices/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('/banner_doctor.jpg');">
  <div class="banner-container">
    <h1>Kenkou Match helps <strong>you find</strong> <strong>local medical specialists.</strong></h1>
    <p>Communicate with Japanese doctors with confidence.</p>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="h2 my-3 d-flex justify-content-center"> Search for a Specialty </h1>
      <div data-controller="search-practices">
        <%= form_with url: practices_path, method: :get, html: {class: "mb-4", data: { search_practices_target: "form" }} do |f| %>
          <!-- How to write an action in regular HTML
          <input class="btn" type="text" data-action="keyup->search-practices#update">
          <input class="btn" type="text" data-search-practices-target="input"> -->
          <%= f.text_field :query,
                            # placeholder: "Type a Practice, Specialty, or Symptom",
                           class: "form-control",
                           value: params[:query],
                           data: {
                            action: "keyup->search-practices#update",
                            search_practices_target: "input"
                           },
                           placeholder: "Type a symptom, practice, or specialty."

                           %>
        <% end %>
        <%# <div class='scrollable'> %>
        <div data-search-practices-target='list'>
          <%= render "list", practices: @practices %>
        </div>
        <%# </div> %>
      </div>
      <div class="practices-wrapper" data-controller="homepage-description">
        <%= render "descriptor"%>
      </div>
    </div>
  </div>
</div>
<!-- end of container -->

app/views/practices/show.html.erb
<div id="banner-content">
  <div></div>
</div>
<div class='container'>
  <div class='row justify-content-center mt-3'>
    <div class='col-12 col-md-6'>
      <div class='bg-white border border-info border-opacity-25 rounded-4 shadow p-3 bg-body rounded'>
        <h2 class="d-flex justify-content-center mt-2 mb-3"><%= @practice.name %></h2>
        <p class="d-flex justify-content-center m-3 mt-2 mb-3 text-wrap" ><%= @practice.info %></p>
        <div class="d-flex">
          <div class="practice-card d-flex justify-content-center align-items-center border border-info rounded-4 shadow p-3 bg-body rounded border-opacity-25 border-light bg-white mt-3 mb-5">
            <div class="practice-infos">
              <img src="<%=image_path("loupe.png") %>" alt="">
              <div>
                <span class="card-text">Find a practice near you</span>
              </div>
              <%= link_to practice_institutions_path(@practice), class: 'fw-bold text-decoration-none practice-card-link' do %>
              </div>
            <% end %>
          </div>
          <div class="practice-card d-flex justify-content-center align-items-center border border-info rounded-4 shadow p-3 bg-body rounded border-opacity-25 border-light bg-white">
            <div class="practice-infos">
              <img src="<%=image_path("translation.png") %>" alt="">
              <div>
                <span class="card-text">Translation helper</span>
              </div>
              <%= link_to new_practice_card_path(@practice), class: 'fw-bold text-decoration-none practice-card-link' do %>
              </div>
            <% end %>
          </div>
        </div>
        <!-- <p class="text-decoration-none d-flex justify-content-center mt-2"><%= link_to 'back', root_path, class:"userList btn btn-outline-danger fixed-width" %></p> -->
      </div>
    </div>
  </div>
</div>