config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "practices#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :practices, only: %i[index show] do
    resources :cards, only: %i[new create]
    resources :institutions, only: %i[index new create]
    get '/institutions/:google_places_id', to: 'institutions#show', as: 'institution'
  end
  resources :cards, only: %i[index show update destroy] do
    resources :studywords, only: :create
    resources :studyphrases, only: :create
    member do
      post :redo, :redophrase
    end
  end
  resources :studywords, only: :index # do
  #   resources :studyphrases, only: :index
  # end
end

app/models/card.rb
class Card < ApplicationRecord
  # association(see also the schema https://kitt.lewagon.com/db/101668)
  belongs_to :user
  belongs_to :practice
  belongs_to :institution, optional: true

  has_many :cardwords
  has_many :studywords, through: :cardwords

  # validation
  validates_presence_of :practice, :originalcontent, :translatedcontent, :cardkeywords
end

app/controllers/cards_controller.rb
require 'miyabi'

class CardsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:redo, :redophrase]
  def index
    # @cards: all cards created by current user(scope ie defined in app/policies)
    @cards = policy_scope(Card) # pundit(authorization)
  end

  def show
    @card = Card.find(params[:id])
    @studywords = Studyword.where(user_id: current_user.id)
    @studyphrases = Studyphrase.where(user_id: current_user.id)
    authorize @card
    @jinput = @card.translatedcontent.to_kanhira
    cards_parse_service = CardsParseService.new
    @keywords = cards_parse_service.parse_content_keys(@card.cardkeywords)
    @phrases = cards_parse_service.parse_content_phrases(@card.cardphrases)
  end

  def new
    @card = Card.new
    @institution = Institution.find(params[:institution_id]) unless params[:institution_id].nil?
    @card.user = current_user
    @practice = Practice.find(params[:practice_id])
    authorize @card # pundit(authorization)
  end

  def create
    @practice = Practice.find(params[:practice_id])
    @card = Card.new(card_params)

    # card needs a user and a practice
    @card.user = current_user
    @card.practice = @practice
    @card.institution = Institution.find(params[:card][:institution_id]) unless params[:card][:institution_id].nil?

    authorize @card

    # deepl
    @card.translatedcontent = (DeepL.translate @card.originalcontent, nil, "JA").text
    prompt = keywords_prompt(@card.translatedcontent)
    @openai_service = OpenaiService.new(prompt)

    # keys
    keywords = @openai_service.call
    @cardparse_service = CardsParseService.new(keywords)
    parsed_keywords = @cardparse_service.parse_content
    eng_keys = @cardparse_service.keys_english(parsed_keywords)

    # phrases
    # @openai_service.update(phrases_prompt(eng_keys, @practice.name))
    @openai_service.update(phrases_prompt_new(@card.translatedcontent, @practice.name))
    phrases = @openai_service.call
    @cardparse_service.update(phrases)
    parsed_phrases = @cardparse_service.parse_content

    # save to card
    @card.cardkeywords = parsed_keywords
    @card.cardphrases = parsed_phrases

    # check if valid
    if @card.save
      redirect_to card_path(@card)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def redo
    @card = Card.find(params[:id])
    @studywords = Studyword.where(user_id: current_user.id)
    authorize @card

    jp_words = JSON.parse(@card.cardkeywords).map { |el| el[0] }
    prompt = keywords_prompt3(jp_words, @card.practice.name)
    @openai_service = OpenaiService.new(prompt)

    keywords = @openai_service.call1
    @cardparse_service = CardsParseService.new(keywords)
    parsed_keywords = @cardparse_service.parse_content

    @card.cardkeywords = parsed_keywords.to_json
    @card.save

    @keywords = parsed_keywords
    respond_to do |format|
      format.html
      format.text { render partial: "jkeyword", locals: { keywords: @keywords, studywords: @studywords }, formats: [:html] }
    end
  end

  def redophrase
    @card = Card.find(params[:id])
    authorize @card
    @studyphrases = Studyphrase.where(user_id: current_user.id)
    @cardparse_service = CardsParseService.new
    jp_words = JSON.parse(@card.cardkeywords).map { |el| el[0] }
    @openai_service = OpenaiService.new(phrases_prompt2(jp_words, @card.practice.name))

    phrases = @openai_service.call1
    @cardparse_service.update(phrases)
    parsed_phrases = @cardparse_service.parse_content
    @card.cardphrases = parsed_phrases.to_json
    @card.save

    @phrases = @cardparse_service.parse_content_phrases(parsed_phrases.to_json)
    respond_to do |format|
      format.html
      format.text { render partial: "jphrase", locals: { phrases: @phrases, studyphrases: @studyphrases }, formats: [:html] }
    end
  end

  def update
    raise
  end

  def destroy
    @card = Card.find(params[:id])
    authorize(@card)
    @card.destroy
    redirect_to cards_path
  end

  private

  # strong params

  def card_params
    params.require(:card).permit(:originalcontent)
  end

  # gpt prompts

  def keywords_prompt(input)
    "Analyze this text input describing a patient's symptoms in Japanese. Give me a numbered list of 2-7 relevant keywords from the input. Each list item should include the word in kanji, its english translation, and its pronounciation in kana. Use this format: '日本語 - かな - english'. input: #{input}"
  end

  def keywords_prompt2(words, practice)
    "Give me a numbered list of 4-6 new japanese keywords related to these words, that a patient can use in a #{practice} clinic: #{words}. Each list item should include the word in kanji, its english translation, and its pronounciation in kana. Use this format: '日本語 - かな - english'."
  end

  def keywords_prompt3(words, practice)
    "Give me a numbered list of 4-7 new japanese keywords useful for a patient to use at a #{practice} clinic. They should be related to the sympoms in this list: #{words}. Each list item should include the word in kanji, its english translation, and its pronounciation in kana. Use this format: '日本語 - かな - english'."
  end

  def phrases_prompt(input, practice)
    "Give me a numbered list of 3 useful and varied sentences in Japanese for a first-time patient to use at a #{practice} office, so they can help explain their symptoms. use some of the following keywords when creating the sentences:#{input}. In addition to the Japanese, provide the hiragana, and the english translation, all in this format: '日本語 - ひらがな - english'."
  end

  def phrases_prompt_new(input, practice)
    "Give me a numbered list of 4 useful sentences in Japanese for a first-time patient to use at a #{practice} office to explain their symptoms. These are their symptoms in Japanese: #{input}. Provide standard Japanese with Kanji, hiragana, and the english translation, all in this format: '日本語 - ひらがな - english'."
  end

  def phrases_prompt2(input, practice)
    "Give me a numbered list of 3-4 useful and varied sentences in Japanese for a first-time patient to use at a #{practice} office, that help explain their symptoms. use some of the following keywords when creating the sentences:#{input}. Provide standard Japanese with Kanji, hiragana, and the english translation, all in this format: '日本語 - ひらがな - english'."
  end
end

app/views/cards/_jkeyword.html.erb
  <%keywords.each do |kwrd|%>
  <div class="<%= studywords.find_by(english: kwrd[2]).nil? ? 'card-show-key' : 'card-show-key alt' %>">
    <div class="jcontainer">
      <div class="key1" data-savewordbutton-target="kna"><%=kwrd[1]%></div>
      <div class="key2" data-savewordbutton-target="knj"><%=kwrd[0]%></div>
    </div>
    <div class="key3" data-savewordbutton-target="eng"><%=kwrd[2]%></div>
    <button class="addword" data-controller="addwordbutton" data-action="click->addwordbutton#toggleSave" data-addwordbutton-target="button"><%= studywords.find_by(english: kwrd[2]).nil? ? '+' : 'o' %></button>
  </div>
<%end%>
<div class="saveword-container">
  <button class="saveword" data-action="click->savewordbutton#saveWords">Save Favorites</button>
</div>

app/views/cards/_jphrase.html.erb
<%phrases.each do |phrase|%>
  <div class="card-show-phrase">
    <div class="<%= studyphrases.find_by(english: phrase[2]).nil? ? 'card-show-phrase-top' : 'card-show-phrase-top alt' %>">
      <div></div>
      <div class="p1"><%=phrase[2]%></div>
      <button class="addphrase" data-controller="addphrasebutton" data-action="click->addphrasebutton#toggleSave" data-addphrasebutton-target="button"><%= studyphrases.find_by(english: phrase[2]).nil? ? '+' : 'o' %></button>
    </div>
    <div class="card-show-phrase-sub">
      <div class="p2"><%=phrase[1]%></div>
      <div class="p3"><%=phrase[0]%></div>
    </div>
  </div>
<%end%>
<div class="saveword-container">
  <button class="saveword" data-action="click->savephrasebutton#savePhrases">Save Favorites</button>
</div>

app/views/cards/index.html.erb
<%# <h1 class="text-center">your cards</h1> %>
<div id="banner-content">
  <div></div>
</div>
<div class="container">
  <h1 class="index-header pb-0"><i class="fa-regular fa-clipboard" style="padding: 8px">  </i>Your Cards</h1>
  <%# <i>view cards you've created</i> %>
  <div class="cards pt-0 p-4">
    <% @cards.each do |card| %>
      <div class="cards-index-card text-center d-flex flex-direction: column justify-content-around p-1 mt-2">
        <div>
          <%= link_to card_path(card), class: "trash-icon", data: {class: "trash-icon", turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </div>
        <p class="index-content m-3"><%= card.originalcontent %></p>
        <div class="card-title">
          <span>#<%= card.practice.name %></span>
        </div>
        <p><%= card.created_at.strftime('%Y-%m-%d')  %></p>
        <%= link_to("view card", card_path(card), {class: "btn custom-button border-color-none"}) %>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-center mt-5">
    <%= link_to "back", :back , {:class=>"btn btn-outline-danger"} %>
  </div>
</div>

app/views/cards/new.html.erb
<div id="banner-content">
  <div></div>
</div>
<div class='container' data-controller='spinner'>
  <div id="overlay" data-spinner-target="overlay">
    <div class="spinner" data-spinner-target="spinner"></div>
  </div>
  <%# <div data-spinner-target='spinner' class="spinner"></div> %>
  <div class='row justify-content-center mt-3'>
    <div class='col-12 col-md-6'>
      <div class="bg-white border border-info border-opacity-25 rounded-4 shadow p-3 bg-body rounded">
        <div class="create-inst-infos justify-content-center px-2">
          <%if @institution.present?%>
            <div class="instdisp">
              <p class="mb-0"><span class="head">Clinic:</span></p>
              <p class="mb-0"><span id="in"><%=@institution.name%></span></p>
            </div>
          <%end%>
          <div class="instdisp">
            <p class="mb-0"><span class="head">Practice:</span></p>
            <p class="mb-0"><span id="pn"><%=@practice.name%></span></p>
          </div>
        </div>
        <h2 class="d-flex justify-content-center p-3">Create a Kenkou Card</h2>
        <div class="create-infos justify-content-center">
          <p>Kenkou Match offers an ai-assisted 'study' card to help you describe your symptoms in Japanese.</p>
          <p>Enter your symptoms in the field below. <strong>Consider your phrasing</strong> - <i>Short prompts will return short responses.</i></p>
          <p>Instead of <span id="ex1">I have a headache</span>, consider saying <span id="ex2">I've had a headache for three days and the pain is most severe in the evening</span>.</p>
        </div>
        <%= simple_form_for [@practice, @card] do |f| %>
          <%= f.input :originalcontent, label: false, input_html: { maxlength: 150, placeholder: "Please describe your symptoms as specifically as possible" } %>
          <% unless @institution.nil? %>
            <%= f.input :institution_id, :as => :hidden, :input_html => { :value => @institution.id}%>
          <% end %>
          <div class='d-flex justify-content-between p-3'>
            <%= link_to "back", :back , {:class=>"btn btn-outline-danger fixed-width"} %>
            <%= f.submit "create card", class: "btn custom-button fixed-width",  data: { action: "click->spinner#showLoadingSpinner" } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cards/show.html.erb
<div class="card-show-body">
  <div id="banner-content">
    <div></div>
  </div>
  <div>
    <h1><%=@card.practice.name%> Card</h1>
    <% card_date = @card.created_at.strftime('%Y-%m-%d') %>
    <i>Created on: <%= card_date %></i>
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-6 col-sm-12">
        <div class="card-show-container">
          <%if @card.institution.present?%>
            <div class="inner-header">
              <h1>You're Going To:</h1>
            </div>
            <div class="card-show-element">
              <h3><%="#{@card.institution.name}"%></h3>
              <%# <%=  link_to 'detailed information', practice_institution_path(@card.practice, @card.institution.google_places_id)%>
              <div class="card-element-show-info">
                <p><i class="fa-solid fa-location-dot"></i>  <%=@card.institution.address%></p>
                <p><i class="fa-solid fa-phone"></i> <%= @card.institution.phone %></p>
                <p><i class="fa-solid fa-earth-americas"></i>  <a href=<%= @card.institution.website %>><%=@card.institution.website%></a></p>
                </div>
                <div class="saveword-container">
                  <%= link_to("View clinic", practice_institution_path(@card.practice, @card.institution.google_places_id), {class: "btn saveword fixed-width"}) %>
                </div>
              </div>
            <%end%>
            <div class="inner-header">
              <h1 class="mb-3">Your Input</h1>
            </div>
            <div class="card-show-element">
              <div class="card-element-show-info">
                <h3 class="card-element-text"><%="#{@card.originalcontent}"%></h3>
                <span>
                  <h3 class="card-element-text-japanese"><%="#{@card.translatedcontent}"%></h3>
                </span>
                <span>
                  <h3 class="card-element-text-japanese-kana"><%=@jinput%></h3>
                </span>
              </div>
            </div>
            <div data-controller="edit" data-edit-id-value="<%=@card.id%>">
              <div id="overlay" data-edit-target="overlay">
                <div class="spinner" data-edit-target="spinner"></div>
              </div>
              <div class="inner-header">
                <h1 class="mb-3">Your Keywords</h1>
                <div class="d-flex justify-content-center gap-3 mb-3 align-items-center">
                  <%=form_with url: redo_card_path(@card), data: { action: "submit->edit#edit" } do |form| %>
                  <button type="submit" class="btn custom-button"><i class="fa-solid fa-arrows-rotate" style="color: #ffffff;"></i></button>
                  <%end%>
                  <span class="text-dark">More words related to <%=@card.practice.name%></span>
                </div>
              </div>
              <div data-edit-target="edited" class="card-show-element" data-controller="savewordbutton">
                <%= render "jkeyword", keywords: @keywords, studywords: @studywords %>
              </div>
            </div>
            <div data-controller="editphrase" data-editphrase-id-value="<%=@card.id%>">
              <div id="overlay" data-editphrase-target="overlay">
                <div class="spinner" data-editphrase-target="spinner"></div>
              </div>
              <div class="inner-header">
                <h1 class="mb-3">Useful Phrases</h1>
                <div class="d-flex justify-content-center gap-3 mb-3 align-items-center">
                  <%=form_with url: redophrase_card_path(@card), data: { action: "submit->editphrase#edit" } do |form| %>
                    <button type="submit" class="btn custom-button"><i class="fa-solid fa-arrows-rotate" style="color: #ffffff;"></i></button>
                  <%end%>
                  <span class="text-dark">More phrases related to <%=@card.practice.name%></span>
                </div>
              </div>
              <div data-editphrase-target="phedited" class="card-show-element" data-controller="savephrasebutton">
                <%= render "jphrase", phrases: @phrases, studyphrases: @studyphrases%>
              </div>
            </div>
            <div class="del-btn-container">
              <%= link_to card_path(@card), data: { turbo_method: :delete, turbo_confirm: "delete this card?" } do %>
                <button class="del-btn">
                  <h5 style="color: black;">Delete this Card</h5>
                </button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>